/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { AnimationPreset, QRCodeAnimation } from "./components/bp-qr-code/animations";
export namespace Components {
    interface BpQrCode {
        "animateQRCode": (animation?: AnimationPreset | QRCodeAnimation) => Promise<void>;
        "contents": string;
        "getModuleCount": () => Promise<number>;
        "legacy": boolean;
        "maskXToYRatio": number;
        "moduleColor": string;
        "positionCenterColor": string;
        "positionRingColor": string;
        "protocol": string;
    }
}
declare global {
    interface HTMLBpQrCodeElement extends Components.BpQrCode, HTMLStencilElement {
    }
    var HTMLBpQrCodeElement: {
        prototype: HTMLBpQrCodeElement;
        new (): HTMLBpQrCodeElement;
    };
    interface HTMLElementTagNameMap {
        "bp-qr-code": HTMLBpQrCodeElement;
    }
}
declare namespace LocalJSX {
    interface BpQrCode {
        "contents"?: string;
        "legacy"?: boolean;
        "maskXToYRatio"?: number;
        "moduleColor"?: string;
        "onCodeRendered"?: (event: CustomEvent<any>) => void;
        "positionCenterColor"?: string;
        "positionRingColor"?: string;
        "protocol"?: string;
    }
    interface IntrinsicElements {
        "bp-qr-code": BpQrCode;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "bp-qr-code": LocalJSX.BpQrCode & JSXBase.HTMLAttributes<HTMLBpQrCodeElement>;
        }
    }
}
